# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7d52cfcd5586fa5a86a67301539b3de2"
name = "pinpoint-store-locator"
handle = "pinpoint-store-locator"
application_url = "https://pressed-supplement-substitute-clay.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://pressed-supplement-substitute-clay.trycloudflare.com/auth/callback", "https://pressed-supplement-substitute-clay.trycloudflare.com/auth/shopify/callback", "https://pressed-supplement-substitute-clay.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
